version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/soolo-serv

permissions:
  - object: /home/ubuntu/soolo-serv/
    owner: ubuntu
    group: ubuntu
hooks:
   AfterInstall:
     - location: scripts/deploy.sh