version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/soolo-serv/build/libs

permissions:
  - object: /home/ubuntu/soolo-serv/build/libs/
    owner: ubuntu
    group: ubuntu
hooks:
   AfterInstall:
     - location: scripts/deploy.sh