spring:
  profiles:
    include: aws

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false

  thymeleaf:
    cache: 'false'
