spring:
  datasource:
    url: jdbc:mysql://db-mysql.ckfd9z7bzzcw.ap-northeast-2.rds.amazonaws.com:3306/sparta7?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: hanghae13
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
jwt:
  secret:
    key: eyJzdWIiOiIyMDIzMDUwMzIzMDAiLCJuYW1lIjoiZG9u

kakao:
  userApiUrl: https://kapi.kakao.com/v2/user/me
  authUrl: https://kauth.kakao.com/oauth/token
  logoutUrl: https://kapi.kakao.com/v1/user/logout
  restapiKey: 7592433975f9828ad850a19a2de302cd
  #redirectUrl: http://222.102.175.141:8080/kakao/callback
  redirectUrl: http://localhost:3000/kakao/callback

naver:
  authUrl: https://nid.naver.com/oauth2.0/token
  userApiUrl: https://openapi.naver.com/v1/nid/me
  clientID: D4xwyrZRMr_YjycSFka_
  clientSecret: JJWOPrShdj

cloud:
  aws:
    s3:
      bucket: walkingpuppy7
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAULT7JB2ZZ577R2H7
      secretKey: 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