
jwt:
  secret:
    key: eyJzdWIiOiIyMDIzMDUwMzIzMDAiLCJuYW1lIjoiZG9u

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password: ''
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: 'false'
